APT::FTPArchive::Release::Origin "RFSTAGorigin";
APT::FTPArchive::Release::Label "RFSTAGLabel";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "./";
APT::FTPArchive::Release::Architectures "all armhf arm64";
APT::FTPArchive::Release::Components "main";