#!/usr/bin/env bash
pandoc docs/hello-world.1.md -s -t man > docs/hello-world.1

PACKAGE_NAME=$(dpkg-parsechangelog -S Source)
PACKAGE_VERSION=$(dpkg-parsechangelog -S Version | sed 's/-.*//')
PACKAGE_ARCH="all"
TARGET_FILE_NAME="${PACKAGE_NAME}_${PACKAGE_VERSION}_${PACKAGE_ARCH}.deb"

#export PACKAGE_NAME
#export PACKAGE_VERSION
#export PACKAGE_ARCH
#export TARGET_FILE_NAME

debuild --no-tgz-check -uc -us

mv "../${TARGET_FILE_NAME}" .
git add ${TARGET_FILE_NAME}

# Update Packages & Packages.gz
dpkg-scanpackages --multiversion . > Packages
gzip -k -f Packages

# Release, Release.gpg & InRelease
apt-ftparchive release . > Release
gpg --default-key "7064C0876157CFE6553BEBAD787B4F6C4D7F7AE5" -abs -o - Release > Release.gpg
gpg --default-key "7064C0876157CFE6553BEBAD787B4F6C4D7F7AE5" --clearsign -o - Release > InRelease
