#!/bin/bash

set -e
set -x 
set -v

# This `DEBIAN/postinst` script is run post-installation
echo "postinst" $(hostname) | systemd-cat -t rfstag -p info

#pip3 install -r /home/pi/requirements.txt

# Stop and disable legacy services
# Can't get this to work, so just reboot and nfcserver3 will be gone

#LA1=$(systemctl list-units  --full --all | grep -q 'launch_activ')
#if [ -n "$LA1" ]; then
# 	  systemctl unmask  launch_activ
#    systemctl stop    launch_activ
#    systemctl disable launch_activ
#    echo found  $LA1
#else
#	echo not found $LA1
#fi
#
#NA1=$(systemctl list-units  --full --all | grep -q 'nfcserver3')
#if [ -n "$NA1" ]; then
#    echo found  $LA1 'nfcserver3'
#    systemctl unmask  nfcserver3
#    systemctl stop    nfcserver3
#    systemctl disable nfcserver3
#else
#	echo not found $NA1
#fi

# Start next gen services
# Service is sometimes masked after install, so fix this here
systemctl unmask nfcserver3
# stop any running version, so new one can be run up.
systemctl stop   nfcserver3
# Enable to start by default on reboot: will be started if reader connected.
systemctl enable nfcserver3
systemctl start  nfcserver3

systemctl unmask launch_kiosk2
systemctl stop   launch_kiosk2
systemctl enable launch_kiosk2
systemctl start  launch_kiosk2

systemctl unmask kiosk_beeper
systemctl stop   kiosk_beeper
systemctl enable kiosk_beeper
systemctl start  kiosk_beeper

# Make the system journal persistent if not already done.
#  see https://raspberrypi.stackexchange.com/questions/108411/raspbian-journalctl-only-lists-current-boot-although-syslogs-exist
JDIR=/var/log/journal
if [ ! -d "$JDIR" ];
then
	mkdir -p $JDIR
  systemd-tmpfiles --create --prefix $JDIR
fi

exit 0
