#!/bin/sh
set -e
# Automatically added by dh_systemd_start/13.14.1ubuntu5
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'launch_kiosk2.service' 'sony-reader.service' 'vtapreader.service' >/dev/null || true
fi
# End automatically added section
